version: '3'
services:
  prod_web:
    # DEFINE BUILD CONTEXT.
    build:
        #context: .
        context: ../../
        # DOCKERFILE PATH RELATIVE TO BUILD CONTEXT.
        # dockerfile: ./conf/docker/Dockerfile.prod
        dockerfile: ./conf/docker/Dockerfile
    ports:
       #MAPPING -> "HOST:CONTAINER"
     - "52000:8080"
    container_name: ttg_webapp_prod
    hostname: ttg_webapp_prod
