version: '3'
services:
  net_web:
    # DEFINE BUILD CONTEXT.
    build:
        #context: .
        context: ../../
        # DOCKERFILE PATH RELATIVE TO BUILD CONTEXT.
        dockerfile: ./conf/docker/Dockerfile
    networks:
        net_net:
            ipv4_address: 10.0.0.9
    ports:
       #MAPPING -> "HOST:CONTAINER"
     - "54000:8080"
    container_name: ttg_webapp_net
    hostname: ttg_webapp_net
networks:
    net_net:
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/8
